"""
Auto-generated by toml_codegen.py
Source: config.toml
Do not edit manually - re-run the generator to refresh.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import tomllib


@dataclass
class AppLoggingConfig:
    level: str
    file: str
    rotate: bool

@dataclass
class AppConfig:
    name: str
    version: str
    debug: bool
    max_connections: int
    timeout: float
    logging: AppLoggingConfig

@dataclass
class DatabaseCredentialsConfig:
    username: str
    password: str

@dataclass
class DatabaseConfig:
    host: str
    port: int
    name: str
    pool_size: int
    credentials: DatabaseCredentialsConfig

@dataclass
class ServerConfig:
    host: str
    port: int
    workers: int
    allowed_origins: list[str]

@dataclass
class FeatureFlagsConfig:
    enable_beta: bool
    enable_analytics: bool

@dataclass
class PeppolEndpointsConfig:
    doctype: str
    procid: str

@dataclass
class PeppolConfig:
    smp_url: str
    ENDPOINTS: list[PeppolEndpointsConfig]

@dataclass
class MappingsEntryConfig:
    name: str
    code: str

@dataclass
class RootConfig:
    app: AppConfig
    database: DatabaseConfig
    server: ServerConfig
    feature_flags: FeatureFlagsConfig
    PEPPOL: PeppolConfig
    MAPPINGS: dict[str, MappingsEntryConfig]


def parse_config(path: str | Path = "config.toml") -> RootConfig:
    """Load *path* and return a fully-typed RootConfig."""
    with open(path, "rb") as fh:
        data = tomllib.load(fh)
    return (
        RootConfig(
            app=(
                AppConfig(
                    name=data['app']['name'],
                    version=data['app']['version'],
                    debug=data['app']['debug'],
                    max_connections=data['app']['max_connections'],
                    timeout=data['app']['timeout'],
                    logging=(
                        AppLoggingConfig(
                            level=data['app']['logging']['level'],
                            file=data['app']['logging']['file'],
                            rotate=data['app']['logging']['rotate'],
                        )
                    ),
                )
            ),
            database=(
                DatabaseConfig(
                    host=data['database']['host'],
                    port=data['database']['port'],
                    name=data['database']['name'],
                    pool_size=data['database']['pool_size'],
                    credentials=(
                        DatabaseCredentialsConfig(
                            username=data['database']['credentials']['username'],
                            password=data['database']['credentials']['password'],
                        )
                    ),
                )
            ),
            server=(
                ServerConfig(
                    host=data['server']['host'],
                    port=data['server']['port'],
                    workers=data['server']['workers'],
                    allowed_origins=data['server']['allowed_origins'],
                )
            ),
            feature_flags=(
                FeatureFlagsConfig(
                    enable_beta=data['feature_flags']['enable_beta'],
                    enable_analytics=data['feature_flags']['enable_analytics'],
                )
            ),
            PEPPOL=(
                PeppolConfig(
                    smp_url=data['PEPPOL']['smp_url'],
                    ENDPOINTS=[
                        PeppolEndpointsConfig(**_item)
                        for _item in data['PEPPOL']['ENDPOINTS']
                    ],
                )
            ),
            MAPPINGS={
                _k: MappingsEntryConfig(**_v)
                for _k, _v in data['MAPPINGS'].items()
            },
        )
    )
